on: 
  release:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Dataverse Uploader Action
        uses: IQSS/dataverse-uploader@v1.1
        with:
          DATAVERSE_TOKEN: ${{secrets.DV_Token}}
          DATAVERSE_SERVER: https://dataverse.lib.nycu.edu.tw/
          DATAVERSE_DATASET_DOI: doi:10.57770/IOWGLV
